language: python
python:
  - "3.5"
install: pip install -r ./requirements.txt

script:
  - coverage run --timid --source ./files_by_date/ -m py.test
  - coverage report
  - pylint ./files_by_date/
  - bandit -r ./files_by_date/
