language: python
python:
  - "3.4"
install: python setup.py -q install

script:
  - coverage run --timid --source ./files_by_date/ -m py.test
  - coverage report
  - pylint --rcfile=./._pylintrc ./files_by_date/
  - bandit -r ./files_by_date/
